apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
  # like asking for VIP room
  nodeSelector:
    project: roboshop 
  #this is showing the booking confiramtion 
  toleration:
  - key: "project"  
    operator: "Equal"
    value: "roboshop"
    effect: "NoExecute"