apiVersion: v1
kind: Pod 
metadata:
  name: nginx-affinity
  labels:
    env: tests
spec:
  affinity:
    nodeAffinity:
    # Hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - us-east-1b
            - us-east-1d           
  containers:
  - name: nginx
    image: nginx           